# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestID', models.CharField(max_length=120)),
                ('app_type', models.CharField(max_length=120)),
                ('payload', models.CharField(max_length=240)),
            ],
        ),
    ]
