# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainViewController', '0002_mainviewcontroller_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainviewcontroller',
            name='name',
            field=models.CharField(default='None', max_length=120),
        ),
    ]
